/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package generador.de.numeros;

import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import org.apache.commons.math3.distribution.NormalDistribution;

/**
 *
 * @author victo
 */
public class productosmedios extends javax.swing.JFrame {

    /**
     * Creates new form cuadradosmedios
     */
    public productosmedios() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    ArrayList<Float> media = new ArrayList<>();
    DecimalFormat format = new DecimalFormat("#.####");
    ArrayList<Integer>bits= new ArrayList<>();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        semillaTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        generarBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        semilla2txt = new javax.swing.JTextField();
        getback = new javax.swing.JButton();
        pruebasBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Productos medios");

        semillaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semillaTxtActionPerformed(evt);
            }
        });

        jLabel2.setText("X1: ");

        generarBtn.setText("Generar");
        generarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarBtnActionPerformed(evt);
            }
        });

        TextArea.setColumns(20);
        TextArea.setRows(5);
        jScrollPane1.setViewportView(TextArea);

        jLabel3.setText("X2: ");

        semilla2txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semilla2txtActionPerformed(evt);
            }
        });

        getback.setText("Regresar");
        getback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getbackActionPerformed(evt);
            }
        });

        pruebasBtn.setText("Pruebas estadisticas");
        pruebasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pruebasBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(semillaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addComponent(semilla2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(generarBtn)
                            .addComponent(jLabel1))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(getback))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(pruebasBtn)))
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(semillaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(generarBtn)
                            .addComponent(jLabel3)
                            .addComponent(semilla2txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(pruebasBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(getback)))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarBtnActionPerformed
        // TODO add your handling code here:
        int semilla = 0, semilla2=0,formatSemilla;
        String stringSemilla,CentroNumero;
        
        try{
            semilla = Integer.parseInt(semillaTxt.getText());
            semilla2= Integer.parseInt(semilla2txt.getText());
        }
        catch(NumberFormatException numberFormatException){
            JOptionPane.showMessageDialog(null,"La semilla no es un numero","Error del sistema",JOptionPane.ERROR_MESSAGE);
        }
        
        
        if(semillaTxt.getText().length()<4){
            JOptionPane.showMessageDialog(null,"La semilla debe ser de 4 digitos","Error del sistema",JOptionPane.ERROR_MESSAGE);
        }
        else{
            boolean Par;
            int Centro;
            System.out.println("Semilla: "+semilla);
            stringSemilla = semillaTxt.getText();
            
            for(int i=0; i<500; i++){
                float semillafinal= (float) (semilla*0.0001);
                media.add(semillafinal);
                TextArea.append("Semilla: "+semilla +"\t"+"R"+i+": "+format.format(semillafinal)+"\n");
                int numDigitos = stringSemilla.length();
                int Cuadrado = semilla * semilla2;
                String stringCuadrado = String.valueOf(Cuadrado);
                int longCuadrado = stringCuadrado.length();
                if(longCuadrado %2 ==1){
                    System.out.println("Cuadrado: "+Cuadrado);
                    Par = false;
                    System.out.println("Par: "+Par);
                    Centro = (longCuadrado/2)+1;
                    System.out.println("Centro: "+Centro);
                    CentroNumero = stringCuadrado.substring(Centro-3,Centro+1);
                    System.out.println("Centro: "+CentroNumero);
                    
                }
                else{
                    System.out.println("Cuadrado: "+Cuadrado);
                    Par= true;
                    System.out.println("Par: "+Par);
                    Centro = (longCuadrado/2);
                    System.out.println("Centro: "+Centro);
                    CentroNumero = stringCuadrado.substring(Centro-2,Centro+2);
                    System.out.println("Centro: "+CentroNumero);
                    
                }
                semilla= semilla2;
                semilla2 = Integer.parseInt(CentroNumero);
                stringSemilla = ""+semilla;
                
            }
        }
 
    }//GEN-LAST:event_generarBtnActionPerformed

    private void semillaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semillaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semillaTxtActionPerformed

    private void semilla2txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semilla2txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semilla2txtActionPerformed

    private void getbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getbackActionPerformed
        // TODO add your handling code here:
        new NewJFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_getbackActionPerformed

    private void pruebasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pruebasBtnActionPerformed
        // TODO add your handling code here:
        
         //Media
        float media1 = 0;
        for(int i=0;i<media.size();i++){
            media1+= media.get(i);
        }
        float mediafinal = media1/media.size();
        
        //Varianza
        float rango;
        float varianza = 0;
        for(int i=0; i<media.size();i++){
            
            rango = (float) Math.pow(media.get(i)-mediafinal,2);
            varianza+= rango;
        }
        varianza= varianza/media.size();
        
        //Prueba de corridas
        float confianza= (float) 0.95;
        float alfa =1- confianza;
        String resulCorridas;
        
        
        for (int i=1; i<media.size(); i++){
        if (media.get(i)<=media.get(i-1)){
            bits.add(0);
        }
        else{
            bits.add(1);
        }                      
    }
        
        int corridas,dato;
        corridas = 1;
        dato=bits.get(0);
        
        for (int i=1; i<bits.size(); i++){
        if (bits.get(i) != dato){
            corridas++;
            dato = bits.get(i);
        }
    }
        double z;
        z= Math.abs((corridas-mediafinal)/Math.sqrt(varianza));
        NormalDistribution normal = new NormalDistribution();
        double  zn =  normal.inverseCumulativeProbability(1-alfa/2);
        if (z < zn){
        resulCorridas= "No se rechaza que son independientes.";
    }
    else{
        resulCorridas="No pasa la prueba de corridas";
    }
        
        //Chi cuadrada
 
  ArrayList<Float> range1 = new ArrayList<>();
  ArrayList<Float> range2 = new ArrayList<>();
  ArrayList<Float> range3 = new ArrayList<>();
  ArrayList<Float> range4 = new ArrayList<>();
  ArrayList<Float> range5 = new ArrayList<>();
  ArrayList<Float> range6 = new ArrayList<>();
  ArrayList<Float> range7 = new ArrayList<>();
  ArrayList<Float> range8 = new ArrayList<>();
  ArrayList<Float> range9 = new ArrayList<>();
  ArrayList<Float> range10 = new ArrayList<>();
  
  

  int n = media.size();
  float m = (float) Math.pow(n,2);

  // Range 1
  media.forEach((num) -> {
    if (num >= 0 && num < 0.1) range1.add(num);
    if (num >= 0.1 && num < 0.2) range2.add(num);
    if (num >= 0.2 && num < 0.3) range3.add(num);
    if (num >= 0.3 && num < 0.4) range4.add(num);
    if (num >= 0.4 && num < 0.5) range5.add(num);
    if (num >= 0.5 && num < 0.6) range6.add(num);
    if (num >= 0.6 && num < 0.7) range7.add(num);
    if (num >= 0.7 && num < 0.8) range8.add(num);
    if (num >= 0.8 && num < 0.9) range9.add(num);
    if (num >= 0.9 && num <= 1) range10.add(num);
  });
ArrayList<ArrayList> ranges = new ArrayList<>();
  ranges.add(range1);
  ranges.add(range2);
  ranges.add(range3);
  ranges.add(range4);
  ranges.add(range5);
  ranges.add(range6);
  ranges.add(range7);
  ranges.add(range8);
  ranges.add(range9);
  ranges.add(range10);
  
  float sumatoria=(float) 0.000;
  for(int i=0; i<ranges.size();i++){
    float oi= ranges.get(i).size();
    float ei = m;
    float x= ((ei-oi)* (ei-oi))/ei;
    sumatoria+= x;
  }
  
  
  
  //Prueba de poker
  
  /*
	{
		int vec[],vec_fo[];
		double vec_fei[],x02=0,xan1,pmano[]={0.324,0.504,0.108,0.072,0.009,0.0045,0.0001};
		int N=periodo;
		vec=new int[periodo];
		vec_fo=new int[7];
		vec_fei=new double[7];
		for(int i=0;i<periodo;i++)
		{
			vec[i]=(int)(nps[i]*100000);
		}
		getfo(vec,vec_fo);
		for(int i=0;i<vec_fo.length;i++)
		{
			vec_fei[i]=pmano[i]*N;
		}
		rodar(vec_fo,vec_fei);
		for(int i=0;vec_fei[i]<vec_fei.length;i++)
		{
			x02+=Math.pow(vec_fo[i]-vec_fei[i],2)/vec_fei[i];
		}
		xan1=Chi2.getchi2().ObtenerChi(alfa, n-1);
		if(x02<xan1){

                        return true;
        }
  */

    String poker= "No pasa la prueba de poker";

        
        
        
        //Mensaje con todo
        JOptionPane.showMessageDialog(this, "La media es: "+format.format(mediafinal)+"\n"+
                "La varianza es: "+format.format(varianza)+"\n"+
                resulCorridas+"\n"+
                "Chi cuadrada: "+sumatoria+"\n"+
                "Prueba de poker: "+poker,"Pruebas estadisticas",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_pruebasBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(productosmedios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(productosmedios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(productosmedios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(productosmedios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new productosmedios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextArea;
    private javax.swing.JButton generarBtn;
    private javax.swing.JButton getback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pruebasBtn;
    private javax.swing.JTextField semilla2txt;
    private javax.swing.JTextField semillaTxt;
    // End of variables declaration//GEN-END:variables
}
